name: Create Release and Build Artifacts

on:
  push:
    branches:
      - "release/v*" # Trigger on branches like release/v1.0.0, release/v1.2.3-alpha

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      PIO_ENV: esp32_fancontrol # Your PlatformIO environment name from platformio.ini
      # Filename for the downloaded CA certificate
      CA_CERT_FILENAME: "github_root_ca.pem"
      GITHUB_API_HOST: "api.github.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9" # PlatformIO recommends Python 3.9+

      - name: Install PlatformIO Core and OpenSSL
        run: |
          pip install -U platformio
          sudo apt-get update && sudo apt-get install -y openssl

      - name: Install project dependencies
        run: pio pkg install --global # Installs libraries globally in the runner

      - name: Create data directory if it doesn't exist
        run: mkdir -p data

      - name: Download GitHub API Root CA Certificate
        run: |
          echo "Attempting to download Root CA for ${{ env.GITHUB_API_HOST }}..."
          openssl s_client -showcerts -connect ${{ env.GITHUB_API_HOST }}:443 -servername ${{ env.GITHUB_API_HOST }} < /dev/null 2>/dev/null | \
          awk '
            /BEGIN CERTIFICATE/ {
              buffer=""
              in_cert=1
            }
            in_cert {
              buffer = buffer $0 "\n"
            }
            /END CERTIFICATE/ {
              if (in_cert) {
                last_cert=buffer
                in_cert=0 
              }
            }
            END {
              if (last_cert != "") {
                print "Found a certificate, saving as data/${{ env.CA_CERT_FILENAME }}"
                printf "%s", last_cert > "data/${{ env.CA_CERT_FILENAME }}"
              } else {
                echo "Error: Could not extract any certificate from ${{ env.GITHUB_API_HOST }}"
                exit 1
              }
            }
          '
          if [ ! -s data/${{ env.CA_CERT_FILENAME }} ]; then
            echo "Error: Failed to download or CA certificate file (data/${{ env.CA_CERT_FILENAME }}) is empty."
            exit 1
          fi
          echo "GitHub API Root CA certificate downloaded successfully to data/${{ env.CA_CERT_FILENAME }}."
          echo "--- Certificate Content (first 5 lines) ---"
          head -n 5 data/${{ env.CA_CERT_FILENAME }}
          echo "----------------------------------------"
          ls -l data/
        shell: bash

      - name: Build Firmware
        run: pio run -e ${{ env.PIO_ENV }}

      - name: Build Filesystem Image (includes downloaded CA cert)
        run: pio run -e ${{ env.PIO_ENV }} --target buildfs

      - name: Get Version from Branch
        id: get_version
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/release/}"
          echo "VERSION_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
        shell: bash

      - name: Determine Asset Names and Prepare Files
        id: asset_names
        run: |
          # Asset names for the version-specific release
          VERSIONED_FIRMWARE_NAME="firmware_${{ env.PIO_ENV }}_${{ env.VERSION_TAG }}.bin"
          VERSIONED_SPIFFS_NAME="spiffs_${{ env.PIO_ENV }}_${{ env.VERSION_TAG }}.bin"

          # Asset names for the 'latest' release
          LATEST_FIRMWARE_NAME="firmware_${{ env.PIO_ENV }}_latest.bin"
          LATEST_SPIFFS_NAME="spiffs_${{ env.PIO_ENV }}_latest.bin"

          # Output versioned names to GITHUB_ENV for the version-specific release
          echo "VERSIONED_FIRMWARE_ASSET_NAME=${VERSIONED_FIRMWARE_NAME}" >> $GITHUB_ENV
          echo "VERSIONED_SPIFFS_ASSET_NAME=${VERSIONED_SPIFFS_NAME}" >> $GITHUB_ENV

          # Output 'latest' names to GITHUB_ENV for the 'latest' release
          echo "LATEST_FIRMWARE_ASSET_NAME=${LATEST_FIRMWARE_NAME}" >> $GITHUB_ENV
          echo "LATEST_SPIFFS_ASSET_NAME=${LATEST_SPIFFS_NAME}" >> $GITHUB_ENV

          # Copy built files to versioned names
          echo "Copying .pio/build/${{ env.PIO_ENV }}/firmware.bin to ${VERSIONED_FIRMWARE_NAME}"
          cp .pio/build/${{ env.PIO_ENV }}/firmware.bin "${VERSIONED_FIRMWARE_NAME}"
          echo "Copying .pio/build/${{ env.PIO_ENV }}/spiffs.bin to ${VERSIONED_SPIFFS_NAME}"
          cp .pio/build/${{ env.PIO_ENV }}/spiffs.bin "${VERSIONED_SPIFFS_NAME}"

          # Copy built files to 'latest' names (these will be the same content as versioned ones for this run)
          echo "Copying .pio/build/${{ env.PIO_ENV }}/firmware.bin to ${LATEST_FIRMWARE_NAME}"
          cp .pio/build/${{ env.PIO_ENV }}/firmware.bin "${LATEST_FIRMWARE_NAME}"
          echo "Copying .pio/build/${{ env.PIO_ENV }}/spiffs.bin to ${LATEST_SPIFFS_NAME}"
          cp .pio/build/${{ env.PIO_ENV }}/spiffs.bin "${LATEST_SPIFFS_NAME}"

          echo "Listing files in current directory:"
          ls -l
        shell: bash

      - name: Create Release from Branch
        id: create_tagged_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Release ${{ env.VERSION_TAG }}
          body: |
            Automated release for version ${{ env.VERSION_TAG }} (from branch ${{ github.ref_name }}).
            Contains firmware and SPIFFS filesystem image.
            The SPIFFS image includes the Root CA certificate for `${{ env.GITHUB_API_HOST }}` (downloaded during build) as `${{ env.CA_CERT_FILENAME }}`.
          draft: false
          prerelease: ${{ contains(env.VERSION_TAG, '-') }}
          files: |
            ${{ env.VERSIONED_FIRMWARE_ASSET_NAME }}
            ${{ env.VERSIONED_SPIFFS_ASSET_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete 'latest' Release and Tag if they exist
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create 'latest' Release
        id: create_latest_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          body: |
            This is the latest automated build.
            Based on version: ${{ env.VERSION_TAG }} (from branch ${{ github.ref_name }})
            Contains firmware and SPIFFS filesystem image.
            The SPIFFS image includes the Root CA certificate for `${{ env.GITHUB_API_HOST }}` (downloaded during build) as `${{ env.CA_CERT_FILENAME }}`.
          draft: false
          prerelease: false
          files: |
            ${{ env.LATEST_FIRMWARE_ASSET_NAME }}
            ${{ env.LATEST_SPIFFS_ASSET_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
